### ISSUE TITLE
keyboard accessibility help link

### ISSUE THREAD

**Issue by DAF-WebTech** [qld-gov-au/web-template-release#5]
in the asset named access.html, you have a relative link. 
&lt;a href="/help/accessibility/keyboard.html#section-aria-keyboard-navigation"&gt;Use tab and cursor keys to move around the page (more information)&lt;/a&gt;

This link is broken on our sites because it is relative. Please change the href to www.qld.gov.au/help/accessibility/keyboard.html#section-aria-keyboard-navigation

**Comment by asifaminb** [comment]
This will go in the next SWE release  (SWE 3.1.7)

https://github.com/qld-gov-au/qg-web-template/blob/release-v3.1.7/src/assets/_project/_blocks/layout/header/access.html

**Comment by asifaminb** [comment]
@DAF-WebTech 
We have made this change.
