### ISSUE TITLE
Rogue link styles in _alert.scss

### ISSUE THREAD

**Issue by michaelstrelan-catalyst** [qld-gov-au/web-template-release#6]
I'm working with Queensland Shared Services to implement these styles on https://www.forgov.qld.gov.au/ and found these un-namespaced link styles in _alert.scss.

```
// links
a {
  color: #13578b;
  text-decoration: none;
}
a:focus, a:hover {
  color: #0a2d48;
  text-decoration: underline;
}
a:active, a:hover {
  outline: 0;
}
```
They don't seem to belong here, and the `outline: 0` is problematic when hovering on a focused link. I believe they can simply be removed.

**Comment by asifaminb** [comment]
Hi,

I have removed these styles and included in the next SWE release. 

https://github.com/qld-gov-au/qg-web-template/blob/release-v3.1.6/src/assets/_project/_blocks/components/_alert.scss

**Comment by asifaminb** [comment]
This issue is fixed in the latest release.
